name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *' # Every six hours UTC+3

permissions:
  contents: write

jobs:
  auto-update:
    runs-on: [self-hosted, nixos]

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Update Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update flake inputs
        run: |
          nix flake update
          git add flake.lock
          if ! git diff --cached --quiet; then
            git commit -m "chore: Bump flake inputs"
          fi

      - name: Push changes
        run: |
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
            git push origin HEAD:main
          else
            echo "All up to date. Nothing to do."
          fi
